/**
 * This class is generated by jOOQ
 */
package ru.avito.jooqdbmodel;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.avito.jooqdbmodel.tables.*;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Avito extends SchemaImpl {

    private static final long serialVersionUID = 391618151;

    /**
     * The reference instance of <code>avito</code>
     */
    public static final Avito AVITO = new Avito();

    /**
     * The table <code>avito.calls</code>.
     */
    public final Calls CALLS = ru.avito.jooqdbmodel.tables.Calls.CALLS;

    /**
     * The table <code>avito.comments</code>.
     */
    public final Comments COMMENTS = ru.avito.jooqdbmodel.tables.Comments.COMMENTS;

    /**
     * The table <code>avito.question</code>.
     */
    public final Question QUESTION = ru.avito.jooqdbmodel.tables.Question.QUESTION;

    /**
     * The table <code>avito.shop_category</code>.
     */
    public final ShopCategory SHOP_CATEGORY = ru.avito.jooqdbmodel.tables.ShopCategory.SHOP_CATEGORY;

    /**
     * The table <code>avito.users</code>.
     */
    public final Users USERS = ru.avito.jooqdbmodel.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Avito() {
        super("avito", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Calls.CALLS,
                Comments.COMMENTS,
                Question.QUESTION,
                ShopCategory.SHOP_CATEGORY,
                Users.USERS);
    }
}
