/**
 * This class is generated by jOOQ
 */
package ru.avito.jooqdbmodel;


import ru.avito.jooqdbmodel.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in avito
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>avito.calls</code>.
     */
    public static final Calls CALLS = ru.avito.jooqdbmodel.tables.Calls.CALLS;

    /**
     * The table <code>avito.comments</code>.
     */
    public static final Comments COMMENTS = ru.avito.jooqdbmodel.tables.Comments.COMMENTS;

    /**
     * The table <code>avito.question</code>.
     */
    public static final Question QUESTION = ru.avito.jooqdbmodel.tables.Question.QUESTION;

    /**
     * The table <code>avito.shop_category</code>.
     */
    public static final ShopCategory SHOP_CATEGORY = ru.avito.jooqdbmodel.tables.ShopCategory.SHOP_CATEGORY;

    /**
     * The table <code>avito.users</code>.
     */
    public static final Users USERS = ru.avito.jooqdbmodel.tables.Users.USERS;
}
