var host = "http://"+location.host + "/firecatcher/api/"; // Основной хост URL
var oktell = "http://"+location.host + "firecatcher/oktell/calls?name=Avito_get_file_by_id_conn&attachment=1&startparam1="; // Октелл
var allAgentsURL = 			host + "agent/find"; // Поиск всех агентов в базе
var addAgentURL = 			host + "agent/save"; // Добавление нового агента в базу
var updAgentURL = 			host + "agent/update"; // Обновление информации об агенте
var updateNotesURL = 		host + "agent/notes/update"; // Обновление заметок
var getNotesURL = 			host + "agent/find/id/"; // Найти определенного агента
var getQuestionsURL = 		host + "call/find/questions/"; // Найти звонки по вопросу
var callTypeURL = 			host + "call/find/type/"; // Тип звонка (empty\updated\empty_feedback\full_feedback)
var getCallsURL = 			host + "call/find/user/"; // вывести список звонков по ID клиента
var emptyFeedbackURL = 		host + "call/find/type/empty_feedback/1/"; // пустые фидбеки
var dayCallsURL = 			host + "call/find/agent/"; // звонки за сегодня по агенту
var updateEmptyCalls = 		host + "call/update"; // обновить информацию в звонке
var feedbackSaveURL = 		host + "call/feedback/save"; // обновить информацию о фидбеке
var fullFeedbackURL = 		host + "call/find/type/full_feedback/"; // // URL для заполненных фидбеков
var getCatsURL = 			host + "category/find"; // // URL для категорий
var getCommentsURL = 		host + "comments/find/"; // URL для комментариев по учетке
var postCommentURL = 		host + "comments/save"; //  сохранение комментария
var getQuestionsInfoURL = 	host + "question/find"; // URL по вопросам в базе
var statURL = 				host + "stat/find/"; // статистика
var tagGroupURL = 			host + "taggroup/find"; // список групп тэгов
var addTagGroupURL = 		host + "taggroup/save"; // добавить группу тэгов
var updTagGroupURL = 		host + "taggroup/update"; // обновить информацию по группе тэгов
var tagURL = 				host + "tags/find"; // список тэгов
var addTagURL = 			host + "tags/save"; // добавить тэг
var updTagURL = 			host + "tags/update"; // обновить тэг
var changeTagGroup = 		host + "tags/group"; // изменить группу в тэге