/**
 * This class is generated by jOOQ
 */
package ru.avito.jooqdbmodel.tables;


import org.jooq.*;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.avito.jooqdbmodel.Avito;
import ru.avito.jooqdbmodel.Keys;
import ru.avito.jooqdbmodel.tables.records.CallsRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Calls extends TableImpl<CallsRecord> {

    private static final long serialVersionUID = 1407272265;

    /**
     * The reference instance of <code>avito.calls</code>
     */
    public static final Calls CALLS = new Calls();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CallsRecord> getRecordType() {
        return CallsRecord.class;
    }

    /**
     * The column <code>avito.calls.id</code>.
     */
    public final TableField<CallsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>avito.calls.user_id</code>.
     */
    public final TableField<CallsRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>avito.calls.call_link</code>.
     */
    public final TableField<CallsRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

    /**
     * The column <code>avito.calls.time_begin</code>.
     */
    public final TableField<CallsRecord, Long> TIME_BEGIN = createField("time_begin", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>avito.calls.time_end</code>.
     */
    public final TableField<CallsRecord, Long> TIME_END = createField("time_end", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>avito.calls.avito_link</code>.
     */
    public final TableField<CallsRecord, Long> AVITO_LINK = createField("avito_link", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>avito.calls.question_id</code>.
     */
    public final TableField<CallsRecord, Integer> QUESTION_ID = createField("question_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, Integer> SHOP_CATEGORY_ID = createField("shop_category_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, Boolean> IS_MANAGER = createField("isManager", SQLDataType.BOOLEAN, this, "");
    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, String> CHAIN_ID = createField("chain_id", SQLDataType.VARCHAR.length(100), this, "");
    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, String> COM_ID = createField("com_id", SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, String> TAGS = createField("tags", SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * The column <code>avito.calls.shop_category_id</code>.
     */
    public final TableField<CallsRecord, Boolean> IS_OUT = createField("isOut", SQLDataType.BOOLEAN, this, "");


    /**
     * Create a <code>avito.calls</code> table reference
     */
    public Calls() {
        this("calls", null);
    }

    /**
     * Create an aliased <code>avito.calls</code> table reference
     */
    public Calls(String alias) {
        this(alias, CALLS);
    }

    private Calls(String alias, Table<CallsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Calls(String alias, Table<CallsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Avito.AVITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CallsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CALLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CallsRecord> getPrimaryKey() {
        return Keys.KEY_CALLS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CallsRecord>> getKeys() {
        return Arrays.<UniqueKey<CallsRecord>>asList(Keys.KEY_CALLS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CallsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CallsRecord, ?>>asList(Keys.CALLS_IBFK_1, Keys.CALLS_IBFK_2, Keys.CALLS_IBFK_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Calls as(String alias) {
        return new Calls(alias, this);
    }

    /**
     * Rename this table
     */
    public Calls rename(String name) {
        return new Calls(name, null);
    }
}
