/**
 * This class is generated by jOOQ
 */
package ru.avito.jooqdbmodel.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import ru.avito.jooqdbmodel.Avito;
import ru.avito.jooqdbmodel.Keys;
import ru.avito.jooqdbmodel.tables.records.CommentsRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Comments extends TableImpl<CommentsRecord> {

    private static final long serialVersionUID = 890084304;

    /**
     * The reference instance of <code>avito.comments</code>
     */
    public static final Comments COMMENTS = new Comments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommentsRecord> getRecordType() {
        return CommentsRecord.class;
    }

    /**
     * The column <code>avito.comments.id</code>.
     */
    public final TableField<CommentsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>avito.comments.avito_link</code>.
     */
    public final TableField<CommentsRecord, Long> AVITO_LINK = createField("avito_link", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>avito.comments.user_id</code>.
     */
    public final TableField<CommentsRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>avito.comments.time</code>.
     */
    public final TableField<CommentsRecord, Long> TIME = createField("time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>avito.comments.message</code>.
     */
    public final TableField<CommentsRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(2000), this, "");

    /**
     * Create a <code>avito.comments</code> table reference
     */
    public Comments() {
        this("comments", null);
    }

    /**
     * Create an aliased <code>avito.comments</code> table reference
     */
    public Comments(String alias) {
        this(alias, COMMENTS);
    }

    private Comments(String alias, Table<CommentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Comments(String alias, Table<CommentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Avito.AVITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CommentsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CommentsRecord> getPrimaryKey() {
        return Keys.KEY_COMMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CommentsRecord>> getKeys() {
        return Arrays.<UniqueKey<CommentsRecord>>asList(Keys.KEY_COMMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CommentsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CommentsRecord, ?>>asList(Keys.COMMENTS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Comments as(String alias) {
        return new Comments(alias, this);
    }

    /**
     * Rename this table
     */
    public Comments rename(String name) {
        return new Comments(name, null);
    }
}
