/**
 * This class is generated by jOOQ
 */
package ru.avito.jooqdbmodel.tables.records;


import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;
import ru.avito.jooqdbmodel.tables.Calls;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CallsRecord extends UpdatableRecordImpl<CallsRecord> implements Record13<Integer, Integer, String, Long, Long, Long, Integer, Integer,Boolean, String, String, String, Boolean> {

    private static final long serialVersionUID = -226378167;

    /**
     * Setter for <code>avito.calls.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>avito.calls.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>avito.calls.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>avito.calls.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>avito.calls.call_link</code>.
     */
    public void setCallLink(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>avito.calls.call_link</code>.
     */
    public String getCallLink() {
        return (String) get(2);
    }

    /**
     * Setter for <code>avito.calls.time_begin</code>.
     */
    public void setTimeBegin(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>avito.calls.time_begin</code>.
     */
    public Long getTimeBegin() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>avito.calls.time_end</code>.
     */
    public void setTimeEnd(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>avito.calls.time_end</code>.
     */
    public Long getTimeEnd() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>avito.calls.avito_link</code>.
     */
    public void setAvitoLink(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>avito.calls.avito_link</code>.
     */
    public Long getAvitoLink() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>avito.calls.question_id</code>.
     */
    public void setQuestionId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>avito.calls.question_id</code>.
     */
    public Integer getQuestionId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>avito.calls.shop_category_id</code>.
     */
    public void setShopCategoryId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>avito.calls.shop_category_id</code>.
     */
    public Integer getShopCategoryId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>avito.calls.isManager</code>.
     */
    public void setIsManager(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>avito.calls.isManager</code>.
     */
    public Boolean getIsManager() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>avito.calls.chain_id</code>.
     */
    public void setChainId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>avito.calls.chain_id</code>.
     */
    public String getChainId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>avito.calls.com_id</code>.
     */
    public void setComId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>avito.calls.com_id</code>.
     */
    public String getComId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>avito.calls.com_id</code>.
     */
    public void setFileName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>avito.calls.com_id</code>.
     */
    public String getFileName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>avito.calls.com_id</code>.
     */
    public void setIsOut(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>avito.calls.com_id</code>.
     */
    public Boolean getIsOut() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, Long, Long, Long, Integer, Integer, Boolean, String, String, String, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, Long, Long, Long, Integer, Integer, Boolean, String, String, String, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Calls.CALLS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Calls.CALLS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Calls.CALLS.CALL_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Calls.CALLS.TIME_BEGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Calls.CALLS.TIME_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Calls.CALLS.AVITO_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Calls.CALLS.QUESTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Calls.CALLS.SHOP_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Calls.CALLS.IS_MANAGER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Calls.CALLS.CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Calls.CALLS.COM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Calls.CALLS.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return Calls.CALLS.IS_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCallLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getTimeBegin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTimeEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getAvitoLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getQuestionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getShopCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getIsManager();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() { return getChainId();  }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getComId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getIsOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value3(String value) {
        setCallLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value4(Long value) {
        setTimeBegin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value5(Long value) {
        setTimeEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value6(Long value) {
        setAvitoLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value7(Integer value) {
        setQuestionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value8(Integer value) {
        setShopCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value9(Boolean value) {
        setIsManager(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value10(String value) {
        setChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value11(String value) {
        setComId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value12(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord value13(Boolean value) {
        setIsOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CallsRecord values(Integer value1, Integer value2, String value3, Long value4, Long value5, Long value6, Integer value7, Integer value8, Boolean value9, String value10, String value11, String value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CallsRecord
     */
    public CallsRecord() {
        super(Calls.CALLS);
    }

    /**
     * Create a detached, initialised CallsRecord
     */
    public CallsRecord(Integer id, Integer userId, String callLink, Long timeBegin, Long timeEnd, Long avitoLink, Integer questionId, Integer shopCategoryId, Boolean isManager, String chain_id, String com_id, String file_name, Boolean isOut) {
        super(Calls.CALLS);

        set(0, id);
        set(1, userId);
        set(2, callLink);
        set(3, timeBegin);
        set(4, timeEnd);
        set(5, avitoLink);
        set(6, questionId);
        set(7, shopCategoryId);
        set(8, isManager);
        set(9, chain_id);
        set(10, com_id);
        set(11, file_name);
        set(12, isOut);
    }
}
